services:
  financial-ai:
    container_name: financial-ai
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - BUCKET_NAME=rifai-ai-bucket  # override jika perlu
      - BEDROCK_REGION=us-east-1     # atau tambahan khusus
    restart: unless-stopped